# Generated by Django 4.2.23 on 2025-06-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('genero', models.CharField(blank=True, max_length=50, null=True, verbose_name='Gênero')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível para Empréstimo')),
                ('curso_relacionado', models.CharField(blank=True, help_text='Curso ao qual o livro está mais relacionado (ex: Sistemas de Informação, Administração).', max_length=100, null=True, verbose_name='Curso Relacionado')),
                ('ano_publicacao', models.IntegerField(blank=True, null=True, verbose_name='Ano de Publicação')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['titulo'],
            },
        ),
    ]
