# Generated by Django 4.2.23 on 2025-06-28 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateTimeField(auto_now_add=True, verbose_name='Data de Empréstimo')),
                ('data_devolucao_prevista', models.DateTimeField(verbose_name='Data de Devolução Prevista')),
                ('data_devolucao_real', models.DateTimeField(blank=True, null=True, verbose_name='Data de Devolução Real')),
                ('status', models.CharField(choices=[('emprestado', 'Emprestado'), ('devolvido', 'Devolvido'), ('atrasado', 'Atrasado')], default='emprestado', max_length=20, verbose_name='Status do Empréstimo')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Aluno')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='livros.livro', verbose_name='Livro')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'ordering': ['-data_emprestimo'],
            },
        ),
    ]
